# use ubuntu (16.04) environment
dist: xenial

language: go

env:
  - GO111MODULE=on

go:
  - 1.x
  - 1.13.x
  - 1.14.x
  - master

git:
  depth: 1

install: true

notifications:
  email: false

script:
  - go test -v -race ./...
