name: Tests

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  go-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19"

      - name: Test
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: (Codecov) Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          flags: unittests

      - name: (DeepSource) Upload coverage
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: go
          coverage-file: ./coverage.out
          dsn: ${{ secrets.DEEPSOURCE_DSN }}